language: python
python:
- '3.5'
addons:
  postgresql: '9.4'
before_install:
- pip install coverage
- pip install coveralls
install:
- pip install -r requirements/dev.txt
before_script:
- createdb -U postgres openstax
script:
- coverage run manage.py test --liveserver=localhost:8001 --verbosity=2 --settings=openstax.settings.dev
after_success:
- coveralls
notifications:
  email: false
sudo: false
