language: python
python:
- '3.5'
cache: pip
addons:
  postgresql: '9.4'
before_install:
- openssl aes-256-cbc -K $encrypted_1a9b00072244_key -iv $encrypted_1a9b00072244_iv -in openstax/settings/local.py.travis -out openstax/settings/local.py -d
- pip install coverage
- pip install codecov
install:
- pip install -r requirements/dev.txt
before_script:
- createdb -U postgres openstax
script:
- coverage run manage.py test --verbosity=2 --settings=openstax.settings.test
after_success:
- codecov
notifications:
  email: false
sudo: false
