language: python
python:
  - "3.5"
addons:
  postgresql: "9.4"
before_install:
  - pip install coverage
  - pip install coveralls
install:
  - pip install -r requirements/dev.txt
before_script:
  - createdb -U postgres openstax
  - python manage.py migrate
script:
  # same as 'python manage.py test books' but with a coverage wrapper
  - coverage run --source=books manage.py test
  - coverage run --source=pages manage.py test
after_success:
  - coveralls
notifications:
  email: false
sudo: false
