language: python
python:
  - "3.5"
addons:
  postgresql: "9.4"
before_install:
  - sudo apt-get update
  - pip install coverage
  - pip install coveralls
install:
  - pip install -r requirements/dev.txt
before_script:
  - sudo createdb -U postgres openstax
  - ./manage.py migrate
script:
  - ./manage.py test
after_success:
  - coveralls
notifications:
  email: false

