name: Tests
env:
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: openstax
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:10
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.2
      - name: Setup
        run: |
          pip install --upgrade pip wheel pip-tools
          createdb -U postgres openstax
          pip-sync requirements/dev.txt
          
      - name: Test
        run: |
          python manage.py test